version: "3.7"

services:

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "dev-secret"
    restart: always

  nestjs:
    build:
      context: ./
      dockerfile: nestjs-dockerfile
    container_name: nestjs
    working_dir: /usr/src/nestjs
    tty: true
    volumes:
      - ./nestjs:/usr/src/nestjs
    command: npm run start:dev
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    restart: always
