version: "3.7"

services:

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      TZ: '${TIME_ZONE}'
    restart: always

  test-postgres:
    image: postgres
    container_name: test-postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: "${TEST_DATABASE_PASSWORD}"
      TZ: '${TIME_ZONE}'
    restart: always

  nestjs:
    build:
      context: ./
      dockerfile: nestjs-dockerfile
    container_name: nestjs
    working_dir: /usr/src/nestjs
    tty: true
    environment:
      TZ: '${TIME_ZONE}'
    volumes:
      - ./nestjs:/usr/src/nestjs
      - type: bind
        source: ./.env
        target: /usr/src/nestjs/.env
    command: npm run start:dev
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    restart: always
